
-- PHASE 7: Advanced Database Programming and Auditing
-- Project: Artisanal Coffee Roastery Management System

-- DROP existing objects to avoid errors
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_block_orders';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_block_products';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_block_inventory';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE HOLIDAYS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE audit_pkg';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create the HOLIDAYS table
CREATE TABLE HOLIDAYS (
  holiday_date DATE PRIMARY KEY,
  description VARCHAR2(100)
);

-- Insert holidays
INSERT INTO HOLIDAYS VALUES (TO_DATE('2025-06-01', 'YYYY-MM-DD'), 'Independence Day');
INSERT INTO HOLIDAYS VALUES (TO_DATE('2025-06-07', 'YYYY-MM-DD'), 'Unity Celebration');

-- Create the AUDIT_LOG table
CREATE TABLE AUDIT_LOG (
  log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id VARCHAR2(50),
  action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  table_name VARCHAR2(50),
  operation VARCHAR2(10),
  status VARCHAR2(10),
  remarks VARCHAR2(200)
);

-- Create package specification
CREATE OR REPLACE PACKAGE audit_pkg AS
  FUNCTION is_restricted RETURN BOOLEAN;
  PROCEDURE log_action(
    p_user_id VARCHAR2,
    p_table_name VARCHAR2,
    p_operation VARCHAR2,
    p_status VARCHAR2,
    p_remarks VARCHAR2
  );
END audit_pkg;
/

-- Create package body
CREATE OR REPLACE PACKAGE BODY audit_pkg AS

  FUNCTION is_restricted RETURN BOOLEAN IS
    v_day VARCHAR2(10);
    v_today DATE := TRUNC(SYSDATE);
    v_exists NUMBER := 0;
  BEGIN
    v_day := TO_CHAR(v_today, 'DY', 'NLS_DATE_LANGUAGE=EN');
    IF v_day IN ('MON', 'TUE', 'WED', 'THU', 'FRI') THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(*) INTO v_exists FROM HOLIDAYS WHERE holiday_date = v_today;
    IF v_exists > 0 THEN
      RETURN TRUE;
    END IF;

    RETURN FALSE;
  END;

  PROCEDURE log_action(
    p_user_id VARCHAR2,
    p_table_name VARCHAR2,
    p_operation VARCHAR2,
    p_status VARCHAR2,
    p_remarks VARCHAR2
  ) IS
  BEGIN
    INSERT INTO AUDIT_LOG (user_id, table_name, operation, status, remarks)
    VALUES (p_user_id, p_table_name, p_operation, p_status, p_remarks);
  END;

END audit_pkg;
/

-- Trigger for ORDERS
CREATE OR REPLACE TRIGGER trg_block_orders
BEFORE INSERT OR UPDATE OR DELETE ON ORDERS
FOR EACH ROW
DECLARE
  v_user VARCHAR2(50) := USER;
BEGIN
  IF audit_pkg.is_restricted THEN
    audit_pkg.log_action(v_user, 'ORDERS', ORA_SYSEVENT, 'DENIED', 'Action not allowed during weekdays or holidays.');
    RAISE_APPLICATION_ERROR(-20001, 'You are not allowed to modify this table during weekdays or holidays.');
  ELSE
    audit_pkg.log_action(v_user, 'ORDERS', ORA_SYSEVENT, 'ALLOWED', 'Action permitted.');
  END IF;
END;
/

-- Trigger for PRODUCTS
CREATE OR REPLACE TRIGGER trg_block_products
BEFORE INSERT OR UPDATE OR DELETE ON PRODUCTS
FOR EACH ROW
DECLARE
  v_user VARCHAR2(50) := USER;
BEGIN
  IF audit_pkg.is_restricted THEN
    audit_pkg.log_action(v_user, 'PRODUCTS', ORA_SYSEVENT, 'DENIED', 'Action not allowed during weekdays or holidays.');
    RAISE_APPLICATION_ERROR(-20002, 'You are not allowed to modify PRODUCTS during weekdays or holidays.');
  ELSE
    audit_pkg.log_action(v_user, 'PRODUCTS', ORA_SYSEVENT, 'ALLOWED', 'Action permitted.');
  END IF;
END;
/

-- Trigger for ROASTERY_COFFEE_INVENTORY
CREATE OR REPLACE TRIGGER trg_block_inventory
BEFORE INSERT OR UPDATE OR DELETE ON ROASTERY_COFFEE_INVENTORY
FOR EACH ROW
DECLARE
  v_user VARCHAR2(50) := USER;
BEGIN
  IF audit_pkg.is_restricted THEN
    audit_pkg.log_action(v_user, 'ROASTERY_COFFEE_INVENTORY', ORA_SYSEVENT, 'DENIED', 'Action not allowed during weekdays or holidays.');
    RAISE_APPLICATION_ERROR(-20003, 'You are not allowed to modify inventory during weekdays or holidays.');
  ELSE
    audit_pkg.log_action(v_user, 'ROASTERY_COFFEE_INVENTORY', ORA_SYSEVENT, 'ALLOWED', 'Action permitted.');
  END IF;
END;
/
